package reports

const (
	GenerateBannersStatisticsReportEndpoint            = "/v2/reports/banners-statistics/generate"
	GenerateBarcodesReportEndpoint                     = "/v1/reports/documents/barcodes/generate"
	GenerateBoostConsolidatedReportEndpoint            = "/v2/reports/boost-consolidated/generate"
	GenerateClosureDocumentsDetalizationReportEndpoint = "/v2/reports/closure-documents/detalization/generate"
	GenerateClosureDocumentsReportEndpoint             = "/v2/reports/closure-documents/generate"
	GenerateCompetitorsPositionReportEndpoint          = "/v2/reports/competitors-position/generate"
	GenerateGoodsFeedbackReportEndpoint                = "/v2/reports/goods-feedback/generate"
	GenerateGoodsMovementReportEndpoint                = "/v2/reports/goods-movement/generate"
	GenerateGoodsPricesReportEndpoint                  = "/v2/reports/goods-prices/generate"
	GenerateGoodsRealizationReportEndpoint             = "/v2/reports/goods-realization/generate"
	GenerateGoodsTurnoverReportEndpoint                = "/v2/reports/goods-turnover/generate"
	GenerateJewelryFiscalReportEndpoint                = "/v2/reports/jewelry-fiscal/generate"
	GenerateKeyIndicatorsReportEndpoint                = "/v2/reports/key-indicators/generate"
	GenerateMassOrderLabelsReportEndpoint              = "/v2/reports/documents/labels/generate"
	GenerateSalesGeographyReportEndpoint               = "/v2/reports/sales-geography/generate"
	GenerateShelfsStatisticsReportEndpoint             = "/v2/reports/shelf-statistics/generate"
	GenerateShipmentListDocumentReportEndpoint         = "/v2/reports/documents/shipment-list/generate"
	GenerateShowsBoostReportEndpoint                   = "/v2/reports/shows-boost/generate"
	GenerateShowsSalesReportEndpoint                   = "/v2/reports/shows-sales/generate"
	GenerateStocksOnWarehousesReportEndpoint           = "/v2/reports/stocks-on-warehouses/generate"
	GenerateUnitedMarketplaceServicesReportEndpoint    = "/v2/reports/united-marketplace-services/generate"
	GenerateUnitedNettingReportEndpoint                = "/v2/reports/united-netting/generate"
	GenerateUnitedOrdersReportEndpoint                 = "/v2/reports/united-orders/generate"
	GenerateUnitedReturnsReportEndpoint                = "/v2/reports/united-returns/generate"
	GetReportInfoEndpoint                              = "/v2/reports/info/{reportId}"
)
